Revert CI file since shakecast-dev is not available

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,15 +27,7 @@ stages:
   - build
   - docs
 
-.shakecast-dev:
-  tags:
-    - shakecast-dev
-
-# BUILD TESTS
-shakecast-dev-test:
-  stage: test
-  extends:
-    - .shakecast-dev
+run tests and coverage:
   coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
   artifacts:
     reports:
@@ -43,6 +35,9 @@ shakecast-dev-test:
         coverage_format: cobertura
         path: coverage.xml
       junit: junit.xml
+  rules:
+    - *fork
+    - *upstream
   script:
     - pip install -e .[test]
     - strec_cfg update --datafolder /home/usgs-user/ --gcmt
@@ -50,11 +45,12 @@ shakecast-dev-test:
     - cp tests/data/slab_data/*.grd /home/usgs-user/slabs/.
     - pytest -x --cov=src/gmprocess/ --cov-report xml:coverage.xml --cov-report term --junitxml junit.xml
     - coverage xml
+  stage: test
 
-shakecast-dev-build:
-  stage: build
-  extends:
-    - .shakecast-dev
+run upload pypi:
+  rules:
+    # Run this job when a tag is created manually
+    - if: $CI_COMMIT_TAG
   script:
     - pip install .[build]
     - python -m build
@@ -63,22 +59,81 @@ shakecast-dev-build:
     - |
       if [ $? -eq 0 ]; then
         echo "check-wheel-contents has passed, uploading to PyPi ..."
-        # python -m twine upload dist/*
+        python -m twine upload dist/*
       else
         echo "check-wheel-contents failed, wheel will not be uploaded to PyPi ..."
       fi
-
-shakecast-dev-docs:
+  stage: build
+pages:
   artifacts:
     paths:
       # The folder that contains the files to be exposed at the Page URL
       - public
-  extends:
-    - .shakecast-dev
-  stage: docs
+  rules:
+    # This ensures that only merges to the default branch will trigger
+    # a pages deploy
+    - <<: *upstream
+      when: on_success
+
   script:
     - pip install .[doc]
     - strec_cfg update --datafolder /home/usgs-user/ --gcmt
     - cd docs
     - bash makedocs.sh
+  stage: docs
+
+# .shakecast-dev:
+#   tags:
+#     - shakecast-dev
+
+# # BUILD TESTS
+# shakecast-dev-test:
+#   stage: test
+#   extends:
+#     - .shakecast-dev
+#   coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
+#   artifacts:
+#     reports:
+#       coverage_report:
+#         coverage_format: cobertura
+#         path: coverage.xml
+#       junit: junit.xml
+#   script:
+#     - pip install -e .[test]
+#     - strec_cfg update --datafolder /home/usgs-user/ --gcmt
+#     - mkdir /home/usgs-user/slabs
+#     - cp tests/data/slab_data/*.grd /home/usgs-user/slabs/.
+#     - pytest -x --cov=src/gmprocess/ --cov-report xml:coverage.xml --cov-report term --junitxml junit.xml
+#     - coverage xml
+
+# shakecast-dev-build:
+#   stage: build
+#   extends:
+#     - .shakecast-dev
+#   script:
+#     - pip install .[build]
+#     - python -m build
+#     - python -m zipfile --list dist/*whl
+#     - check-wheel-contents --package src/gmprocess/ --package-omit src/gmprocess/data/asdf dist/
+#     - |
+#       if [ $? -eq 0 ]; then
+#         echo "check-wheel-contents has passed, uploading to PyPi ..."
+#         # python -m twine upload dist/*
+#       else
+#         echo "check-wheel-contents failed, wheel will not be uploaded to PyPi ..."
+#       fi
+
+# shakecast-dev-docs:
+#   artifacts:
+#     paths:
+#       # The folder that contains the files to be exposed at the Page URL
+#       - public
+#   extends:
+#     - .shakecast-dev
+#   stage: docs
+#   script:
+#     - pip install .[doc]
+#     - strec_cfg update --datafolder /home/usgs-user/ --gcmt
+#     - cd docs
+#     - bash makedocs.sh
 
